//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    { 
        //entity class for Product
        public int productId { get; set; }
        public string productName { get; set; }
        public Nullable<System.DateTime> expDate { get; set; }
        public Nullable<long> price { get; set; }
    }
}
